# Generated by Django 4.1.2 on 2022-10-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='name',
            new_name='model',
        ),
    ]
